### ISSUE TITLE
Feature Request - Compatible with Bottlerocket (containerd)

### ISSUE THREAD

**Issue by vikas027** [aevea/commitsar#410]
I use [Bottlerocket](https://aws.amazon.com/bottlerocket/) AMI on EKS clusters which use `containerd` and not docker socket.

It fails with these errors

```
Build container for action use: '/runner/_work/_actions/aevea/commitsar/v0.16.0/Dockerfile'.
  /usr/local/bin/docker build -t 60e226:7de2787af7e04b038ce49eb6a1a987d8 -f "/runner/_work/_actions/aevea/commitsar/v0.16.0/Dockerfile" "/runner/_work/_actions/aevea/commitsar/v0.16.0"
  Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
  Warning: Docker build failed with exit code 1, back off 8.072 seconds before retry.
  /usr/local/bin/docker build -t 60e226:7de2787af7e04b038ce49eb6a1a987d8 -f "/runner/_work/_actions/aevea/commitsar/v0.16.0/Dockerfile" "/runner/_work/_actions/aevea/commitsar/v0.16.0"
  Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
  Warning: Docker build failed with exit code 1, back off 4.07 seconds before retry.
  /usr/local/bin/docker build -t 60e226:7de2787af7e04b038ce49eb6a1a987d8 -f "/runner/_work/_actions/aevea/commitsar/v0.16.0/Dockerfile" "/runner/_work/_actions/aevea/commitsar/v0.16.0"
  Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Error: Docker build failed with exit code 1
```

**Comment by fallion** [comment]
I'll have a look :)

**Comment by fallion** [comment]
Hi @vikas027 

I was looking at the linked issue and it seems that this one has been resolved?

**Comment by vikas027** [comment]
Hey @fallion  - Sorry, I am a bit late here ;)

The issue still very much exists with `containerd` runtime. Please see my explanation [here](https://github.com/bottlerocket-os/bottlerocket/issues/1714#issuecomment-924419811). Thanks!
